spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/springbatchpractice
      username: hayoung
      password: 1234
      driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false